### ISSUE TITLE
Need ability to modify ObjectMapper created by JacksonJsonPayloadConverter

### ISSUE THREAD

**Issue by kelnos** [temporalio/java-sdk#139]
**Is your feature request related to a problem? Please describe.**

When building a Temporal app using Scala, we need to add jackson-scala-module so it knows how to handle Scala types.  However, we need access to the `ObjectMapper` to do this.

This isn't useful for just Scala; for example, we also have a few other org-specific Jackson modules that we use to make using Twilio-internal JVM types easier with Jackson.

**Describe the solution you'd like**

Two options come to mind:

1. A new constructor for `JacksonJsonPayloadConverter` that allows us to pass our own `ObjectMapper`.
2. A `getObjectMapper()` method that returns the `ObjectMapper` that's already been created, which allows us to augment its configuration.

**Describe alternatives you've considered**

Right now I'm using fragile bits of reflection to fetch the private `ObjectMapper` field to make modifications to it.  Obviously, that's not sustainable.

**Additional context**

 n/a

**Comment by michalbric** [comment]
Same issue with Kotlin data classes.
To save time for anybody until the issue is resolved, the reflection based workaround for Kotlin is as follows:

```kotlin
val jacksonJsonPayloadConverter = JacksonJsonPayloadConverter()
val privateMapperField = JacksonJsonPayloadConverter::class.java.getDeclaredField("mapper");
privateMapperField.isAccessible = true
privateMapperField.set(
    jacksonJsonPayloadConverter,
    ObjectMapper().registerKotlinModule().findAndRegisterModules()
)

val defaultDataConverter =
        DefaultDataConverter(NullPayloadConverter(), ByteArrayPayloadConverter(), jacksonJsonPayloadConverter)
val workflowClientOptions = WorkflowClientOptions.newBuilder()
        .setDataConverter(defaultDataConverter)
        .build()

val client = WorkflowClient.newInstance(service, workflowClientOptions)
```

**Comment by mfateev** [comment]
Public constructor that takes ObjectMapper added to JacksonJsonPayloadConverter by https://github.com/temporalio/java-sdk/pull/150
